version: "3.9"

services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - network
    depends_on:
      -  database
    restart: unless-stopped

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  database:
    image : mongo:latest
    restart: always
    container_name: chat-db
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
    networks:
      - network

networks:
    network: